# Generated by Django 4.2.1 on 2023-07-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_a_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('may_unpublish_product', 'may unpublish a product'), ('can_change_description_product', 'can change the description of any product'), ('can_change_category_product', 'can change the category of any product')], 'verbose_name': 'изделие', 'verbose_name_plural': 'изделия'},
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Признак публикации'),
        ),
    ]
